export const sampleContractData = [
  {
    id: "371b97e16240e6",
    creator_id: "",
    name: "eagerBeaverNFT",
    alias: "eagerBeaverNFT",
    data: [
      {
        name: "mintNFT",
        type: "function",
        inputs: [
          { name: "amount", type: "uint256" },
          { name: "name", type: "string" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["view", "payable"],
      },
      {
        name: "revealCollection",
        type: "function",
        inputs: [{ name: "revealedBaseURI", type: "string" }],
        outputs: [{ name: "tokenId", type: "uint256" }],
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["nonpayable"],
      },
      {
        name: "presaleMint",
        type: "function",
        inputs: [{ name: "_merkleProof", type: "bytes32[]" }],
        outputs: [{ name: "tokenId", type: "uint256" }],
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["payable"],
      },
      {
        inputs: [],
        name: "renounceOwnership",
        outputs: [],
        type: "function",
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["nonpayable"],
      },
      {
        inputs: [
          {
            meta: ["indexed"],
            name: "from",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "to",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "tokenId",
            type: "uint256",
          },
        ],
        name: "Transfer",
        type: "event",
        meta: ["anonymous"],
        comment: "",
        isHidden: false,
        isNative: true,
      },
      {
        name: "Mint",
        type: "event",
        inputs: [{ name: "", type: "", meta: [] }],
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["anonymous"],
      },
      {
        name: "approve",
        type: "function",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "tokenId",
            type: "uint256",
          },
        ],
        outputs: [],
        comment: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "balanceOf",
        type: "function",
        inputs: [{ name: "owner", type: "address" }],
        outputs: [{ name: "", type: "uint256" }],
        comment: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "getApproved",
        type: "function",
        inputs: [{ name: "tokenId", type: "uint256" }],
        outputs: [{ name: "", type: "address" }],
        comment: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "Approval",
        type: "event",
        inputs: [
          {
            meta: ["indexed"],
            name: "owner",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "approved",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "tokenId",
            type: "uint256",
          },
        ],
        comment: "",
        isHidden: false,
        isNative: false,
        meta: ["anonymous"],
      },
    ],
  },
  {
    id: "5761bsgqs561a",
    creator_id: "",
    name: "auctionGuruNFT",
    alias: "auctionGuruNFT",
    data: [
      {
        name: "mintNFT",
        type: "function",
        inputs: [
          { name: "amount", type: "uint256" },
          { name: "name", type: "string" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["view", "payable"],
      },
      {
        name: "revealCollection",
        type: "function",
        inputs: [{ name: "revealedBaseURI", type: "string" }],
        outputs: [{ name: "tokenId", type: "uint256" }],
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["nonpayable"],
      },
      {
        name: "presaleMint",
        type: "function",
        inputs: [{ name: "_merkleProof", type: "bytes32[]" }],
        outputs: [{ name: "tokenId", type: "uint256" }],
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["payable"],
      },
      {
        inputs: [],
        name: "renounceOwnership",
        outputs: [],
        type: "function",
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["nonpayable"],
      },
      {
        inputs: [
          {
            meta: ["indexed"],
            name: "from",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "to",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "tokenId",
            type: "uint256",
          },
        ],
        name: "Transfer",
        type: "event",
        meta: ["anonymous"],
        comment: "",
        isHidden: false,
        isNative: true,
      },
      {
        name: "Mint",
        type: "event",
        inputs: [{ name: "", type: "", meta: [] }],
        comment: "",
        isHidden: false,
        isNative: true,
        meta: ["anonymous"],
      },
      {
        name: "approve",
        type: "function",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "tokenId",
            type: "uint256",
          },
        ],
        outputs: [],
        comment: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "balanceOf",
        type: "function",
        inputs: [{ name: "owner", type: "address" }],
        outputs: [{ name: "", type: "uint256" }],
        comment: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "getApproved",
        type: "function",
        inputs: [{ name: "tokenId", type: "uint256" }],
        outputs: [{ name: "", type: "address" }],
        comment: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "Approval",
        type: "event",
        inputs: [
          {
            meta: ["indexed"],
            name: "owner",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "approved",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "tokenId",
            type: "uint256",
          },
        ],
        comment: "",
        isHidden: false,
        isNative: false,
        meta: ["anonymous"],
      },
    ],
  },
];
